apiVersion: apps/v1
kind: Deployment # Object type
metadata: # Deployment metadata
  name: client-deployment
spec: # Deployment spec
  replicas: 3 # Number of Pod to run
  selector:
    matchLabels: # Tells what pods the deployment will apply to
      component: web 
  template: # Pod template
    metadata: # Pod metadata
      labels:
        component: web
    spec: # Pod spec
      containers:
        - name: client # The name of the container to run in the Pod
          image: stephengrider/multi-client # Image of container
          ports:
            - containerPort: 3000 # Exposed container port