apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip-service
spec:
  type: ClusterIP # Type of Service
  selector:
    component: web # Will manage the access to the Deployment with given key-value pair
  ports:
    - port: 3000 # Access point of the client-cluster-ip-service
      targetPort: 3000 # Will be redirected to the client-deployment's port
