# The image will pull the nginx and apply our config into it
FROM nginx 
# The default command of that image will start the nginx with our config. Thats all!
COPY ./default.conf /etc/nginx/conf.d/default.conf