language: generic
sudo: required
services:
  - docker

before_install: # The tasks that has to done before running the primary work, pre-requisite section.
  - cd ./production-grade-flow/web
  - docker build -t ceamkrier/web -f Dockerfile.dev .

script:
  - docker run -e CI=true ceamkrier/web npm run test -- --coverage # `-- --coverage` flag added to make test script terminate and return status code after ran
  