version: '3'
services: 
  redis-app:
    image: 'ceamkrier/redis'
  node-app:
    restart: 'unless-stoped'
    image: 'ceamkrier/node'
    ports: 
      - "4001:8080" # Port incoming traffic from 4001 to 8080